### ISSUE TITLE
Ensure logging

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-queue#115]
- [x] Adding job to a queue, info level
- [x] Processing a job, info level
- [x] Errors, error level

**Comment by viktorprogger** [comment]
@samdark, should we leave these and only these log points?

**Comment by samdark** [comment]
Yes, I think so.

**Comment by guzich** [comment]
Вот не очень понял, наверное, смысл... Можете подсказать...
Смотрю код класса Queue, там уже есть зависимость от LoggerInterface. При добавлении в очередь ( метод push) вызывается метод debug логгера. Т.е. уже происходит логирование уровня debug. Что нужно в данном случае сделать: продублироваь логирование, но с  уровнем info? Заменить? Или что-то еще что я не понял.
Ничего что на русском или на английском в следующий раз писать?

**Comment by samdark** [comment]
It's better to write in English since Yii community is international.

Debug level should be changed to info level.
