### ISSUE TITLE
Handler have access to the cli output of the worker

### ISSUE THREAD

**Issue by romkatsu** [yiisoft/yii-queue#126]
Workers who process messages from the queue are often run through daemons. For example supervisor.

```
[program:my-queue-program]
command=php yii queue/listen --channel=download-images-queue
stdout_logfile=/logs/download-images-queue.log
```

It is very convenient when there is a log file for one worker.

The log file at the same time contains approximately the following:
```
Start processing queue messages.
Processed 1 queue messages.
```

And I would like to be able to write messages to output from the queue handler. 

I suggest transmitting not only a message to the worker, but also a console logger.

**Comment by viktorprogger** [comment]
You can use dependency injection in your handler, where you can get any logger you want.

**Comment by samdark** [comment]
@romkatsu so... considering @viktorprogger comment, do we need it still?

**Comment by viktorprogger** [comment]
It seems like the question is settled.
