### ISSUE TITLE
channel does't overridden (amqp, withChannel with another adapter does not work ? )

### ISSUE THREAD

**Issue by semsty** [yiisoft/yii-queue#140]
### What steps will reproduce the problem?
see fork pull request (link: https://github.com/semsty/yii3-demo/pull/1)

run `./yii queue-test -s 1`

then check queue list with `rabbitmqctl list_queues -p app`

### What is the expected result?

`
channel-1	1
`

### What do you get instead?

`
yii-queue 	1
`

fix there https://github.com/yiisoft/yii-queue/blob/master/src/QueueFactory.php#L89

```
            return $this->queue->withAdapter($adapter);
```

to

```
            return $this->queue->withAdapter($adapter->withChannel($channel));
```

after that messages pushed into correct channel, but in QueueTestCommand `$channel->getChannelName()` still return `yii-queue`

### Additional info

| Q                | A
| ---------------- | ---
| Version          | master ?
| PHP version      |  8.1
| Operating system |

**Comment by viktorprogger** [comment]
Fixed, thank you!
