### ISSUE TITLE
StreamTarget (stdout) does not work with queue/listen

### ISSUE THREAD

**Issue by semsty** [yiisoft/yii-queue#142]
### What steps will reproduce the problem?

add StreamTarget to logger

run `queue/listen` (with messages to process in the queue) with `-vvv` arg

### What is the expected result?

with `queue/listen -vvv` all messages from logger are visible on stdout

### What do you get instead?

logs are not visible in stdout

### Additional info

| Q                | A
| ---------------- | ---
| Version          | master ?
| PHP version      | 8.1
| Operating system |

**Comment by viktorprogger** [comment]
Thank you for reporting the bug.
It's related to the whole yii console ecosystem, not only to the queue package. The way it could be solved on the application level is to change your logger configuration like this:
```
    LoggerInterface::class => [
        'class' => Logger::class,
        '__construct()' => [
            'targets' => ReferencesArray::from([
                FileTarget::class,
                'target-stdout',
            ]),
        ],
        'setFlushInterval()' => [1],
    ],

    'target-stdout' =>                 [
        'class' => StreamTarget::class,
        'setExportInterval()' => [1],
    ],
```
It won't support different verbosity levels, but will immediately send any logger message to `stdout` (based on logger levels setting).
More general fix is described here: yiisoft/yii-runner-console#38
