### ISSUE TITLE
Avoid parasitic dependencies inside job

### ISSUE THREAD

**Issue by viktorprogger** [yiisoft/yii-queue#51]
For now while using yii2-like jobs with DI autowiring we create them like this:
```php
final class SomeJob implements JobInterface
{
    private ServiceInterface $service;
    private int $data;

    public function __construct($data, ServiceInterface $service)
    {
        $this->source = $service;
        $this->data = $data;
    }

    public function execute(): void
    {
        $this->service->doStuff($this->data);
    }
}
```

It means we will push the whole job to the queue, including `service` dependency, which may be very heavy and contain closures which are hard to serialize.

I propose to change the concept of `Job` and declare it as a `Message`. Message in this case will be an event/DTO and will have to have subscriber(s) which will do stuff with received data. Message handlers will be declared via `EventDispatcher`. This approach is used via [symfony/messenger](https://github.com/symfony/messenger).

**Pros:**
- Message can be any object
- Simple message serialization

**Cons:**
- _I don't see them for now_

-------------------------------------------
Another way is to continue using yii2-like jobs, but execute them through [Injector](https://github.com/yiisoft/injector) to inject dependencies into `execute` method.

**Pros:**
- We still have familiar yii2-like jobs

**Cons:**
- We require jobs to have `execute` method but can't declare an interface for it because of variadic parameter count.

--------------------
The third way to avoid parasitic dependencies inside queue server message is to provide general hardcoded serialization and deserialization way which will allow for `Job` to serialize sensitive data only and to inject dependencies on deserialization.

**Pros:**
- We still have familiar yii2-like jobs
- More control on how to serialize job

**Cons:**
- It is a hard way
- We can't take into consideration some complicated cases
- The second _pro_ is achievable by custom serializer usage in the two other cases.

**Comment by viktorprogger** [comment]
@yiisoft/yii3 need some opinions.

**Comment by xepozz** [comment]
I am fully support your idea to separate an execution and transferring data.
Most of all I liked the first option. But I don't sure that using the `EventDispatcher` would be nice solution for now...

**Comment by samdark** [comment]
> It means we will push the whole job to the queue, including service dependency, which may be very heavy and contain closures which are hard to serialize.

The job payload should be as simple as possible and should not contain platform-specific things such as PHP serialized data or PHP class names.

**Comment by samdark** [comment]
Separating handler from payload is a good idea.

**Comment by samdark** [comment]
Overall there are 2 main use-cases:

1. job + worker: schedule a job, assume it will be completed once.
2. message bus: send a message. It may be reacted to many times.
