### ISSUE TITLE
Move commands

### ISSUE THREAD

**Issue by viktorprogger** [yiisoft/yii-queue#53]
@xepozz suggests to move console commands from this package to `yii-console` to remove `yii-console` configuration from `yii-queue` code and to decouple these packages.

**Comment by viktorprogger** [comment]
I think the commads should stay in this package because the use code from this package and they may be needed only with this package. Otherwise we can move all the commands from all the `yii-*` packages to `yii-console`, and `yii-console` will become a trash with tons of broken commands.

**Comment by xepozz** [comment]
It's my mistake, I'm closing the issue.
