### ISSUE TITLE
Preventing job overlaps

### ISSUE THREAD

**Issue by ruslansp** [yiisoft/yii-queue#75]
Tasks arise when there are several tasks in the queue that do the same thing. For example, you need to index a product (which consists of options, pictures, prices, and so on).
When the price changes, an indexing task is sent, when the name changes, an indexing task is sent, and so on. There will be several tasks in the queue with the same product ID, while processing one task, the previous ones that are in the queue need to be skipped.
Or you just need to limit the execution of certain tasks in time (for example, no more than once a minute)
How do you think this relates to the queue? I think you can do this on events, or provide middleware for workers.

**Comment by samdark** [comment]
I think that's the job of the worker to judge if the job should be done or not based on the object is is going to be performed on.
