### ISSUE TITLE
More convenient way to configure adapters

### ISSUE THREAD

**Issue by viktorprogger** [yiisoft/yii-queue#89]
It's pain now to configure different queue channels in application. In case of `yii-queue-amqp` usage user should create aliased configuration for 5 classes on each channel. This means 50 classes for 10 channels!

I have a suggestion to solve the problem:

- `Queue` class should have `withAdapter(AdapterInterface $adapter)` method
- `AdapterInterface` should have `withChannel(string $channel)` method
- Create a queue factory with the following interface:
```php
interface QueueFactory {
    public function get(?string $channel = null): Queue;
}
```

It will return `Queue` object with either the default adapter when `$channel` is `null`, or a adapter configured with the given channel. It means some configuration array should be passed to the factory. In my vision this array will have channel names as keys and values in one of the formats:
- No key/value pair. The factory will return `$queue->withAdapter($adapter->withChannel($channel))`. This ability should be *disabled* by default in order to prevent user mistakes. User should explicitly allow this behavior.
- A callable that returns `AdapterInterface`. It will be called with the Injector.
- An array configuration of `AdapterInterface` to be passed to the `yiisoft/factory`.

**Comment by samdark** [comment]
Sounds alright.
