### ISSUE TITLE
Use CallableFactory from yii-event instead of it copy

### ISSUE THREAD

**Issue by viktorprogger** [yiisoft/yii-queue#94]
`\Yiisoft\Yii\Queue\Worker\Worker::prepare()` is just a copy of `CallableFactory::prepare()`. I think it's not the last place where we need to create some callable from its definition.
I suggest either move the factory from yii-event to injector, or create a separate package.

**Comment by samdark** [comment]
It is not the job of the injector itself.

Is there a reason why CallableFactory is not used by Worker?

**Comment by viktorprogger** [comment]
Nope, the `yii-event` package is not required by `yii-queue`.

**Comment by samdark** [comment]
Otherwise you'd use it as is?

**Comment by samdark** [comment]
Closed for now. Decided not to do it for now.
